version: "3"
services:
  master:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:8086:80"
    depends_on:
      - back_end
      - front_end

  postgres:
    image: postgres
    volumes:
      - ./db_storage/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password

  back_end:
    image: orbin/temperature-logging-back-end
    depends_on:
      - "postgres"
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:password@postgres:5432/postgres"
    restart: on-failure

  front_end:
    image: orbin/temperature-logging-front-end
